### ISSUE TITLE
nComputing x550 support

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#11]
@cyberorg Does the MSS power sessions for devices such as the X550 (Technical specifications [herein](https://www.ncomputing.com/india/products/xseries/tech-specs))?

**Comment by cyberorg** [comment]
MSS does not serve ncomputing clients directly, those clients will use
remote-desktop to get linux session and browser for offline content.

**Comment by intelliant01** [comment]
Yes, verified. 

It is the similar process to connect with clients from Enjay. But Enjay and nComputing are a less efficient solution as they result in vendor lock-in and also require a powerful and expensive server.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#11
