### ISSUE TITLE
Need support for typing in Gujarati 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#13]
A few users wanted to type in Gujarati in writer but weren't able to despite choosing the installed Gujarati fonts. The language switch option next to the system tray did not include Gujarati. 
How to accomplish the same?

**Comment by cyberorg** [comment]
It is already there documentation is available here: https://help.ubuntu.com/community/ibus

![ibus-typing](https://cloud.githubusercontent.com/assets/1300602/23332073/61d606e0-fb98-11e6-826c-4f77ef99906d.gif)

**Comment by intelliant01** [comment]
Will verify this and close it if working fine in both fc and tc mode.

**Comment by intelliant01** [comment]
Verified.

**Comment by cyberorg** [comment]
Now auto configured, english and all available gujarati keyboards.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#13
