### ISSUE TITLE
Provide internet gateway content filtering

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss-doc#17]
Use external services  such as opendns or those that comes with routers. Claim of MSS being plug 'n play and zero manual configuration by school teacher will not be met by adding complicated services such as dansguardian+squid.

https://freedompenguin.com/articles/how-to/parental-controls-linux-unleashed/

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#17
