### ISSUE TITLE
Reduce technical words in user experience

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#20]
In the boot menu -
Change Fatclient to MSS Client
Thinclient to MSS Legacy Client
and likewise.

**Comment by cyberorg** [comment]
English-Desktop
Gujarati-Desktop
Hindi-Desktop
Legacy-Client
Unsupported-Client

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#20
