### ISSUE TITLE
Build offlineweb index.html as per modules needed

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss-doc#26]
there is new folder /home/mss/offlineweb/mss/indexer/
Any change to index.html should now go in indexer/htmls/*.html and running ./indexer.sh will create index.html

e.g. to remove kalite
mkdir notneeded
mv htmls/5-kalite.html notneeded/
./indexer.sh

Data folders can be removed if desired:
For kalite:
/home/mssadmin/.kalite and remove kalite autostart from /etc/rc.local
For other content in /srv/www/htdocs/mss/ 
spoken-tutorial
computer-masti
textbooks
rachel
xowa (also needs removing/commenting in /etc/rc.local)

**Comment by intelliant01** [comment]
Converted to a wiki - https://github.com/cyberorg/mss/wiki/Build-offlineweb-index.html-as-per-modules-needed

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#6
