### ISSUE TITLE
Offline documentation issues

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#32]
Unzipping and hosting this https://media.readthedocs.org/htmlzip/mss-doc/latest/mss-doc.zip offline has these issues -
1. The navigation menu is flat and does not resemble the online version of rtd hence making it less useful.
2. There seem to be some references to online resources that slow down the loading of the documentation until the request for online resources times out.
3. Can't figure out how to make the translated (for e.g. in Gujarati) manual visible as well.

**Comment by cyberorg** [comment]
1. That is how rtfd exports to html is, nothing we can do about it, to me it seems fine, so it is subjective, it uses html and css mainly, you can customize those and replace whatever rtfd exports.
2. Don't understand what it means, havent come across something like that.
3. Make merge request, it will show up in mss-doc.rtfd.io

**Comment by intelliant01** [comment]
1. No it is not at all fine. All subsections are visible at the same level. You should file an issue with them as it affects the user experience.

2. See the generated html for references to readthedocs.io and you will spot what is amiss or try opening the exported docs in a browser when your system if offline.

3. I am referring to 'gu' export which can be made available offline under the same user manual link.

**Comment by cyberorg** [comment]
![screenshot_2017-04-22-00-34-58-112_org mozilla firefox](https://cloud.githubusercontent.com/assets/1300602/25292454/cc650e58-26f3-11e7-93b2-18f6f288778b.png)
If the default exported result is not acceptable, 1. Customize the theme locally after export or use pdf export, 2. Customize theme on rtfd in your repo 3. Use sphinx locally with other available themes, 4. You are free to file bug yourself 5.Move to any other platform that gives desired output.

MSS at TCV here does not have internet, looks and loads fine here. Screenshot is from my phone, notice no internet.

No idea about Gujarati html export on rtfd.

**Comment by intelliant01** [comment]
> MSS at TCV here does not have internet, looks and loads fine here. Screenshot is from my phone, notice no internet.

Just FYI, see the left navigation menu with and without Internet.

The issue was tagged as #helpwanted and not warranted for the revert above.

**Comment by cyberorg** [comment]
Ref: http://docs.readthedocs.io/en/latest/theme.html
