### ISSUE TITLE
Spoken tutorial content required in Hindi

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#36]
@cyberorg Have a need for spoken tutorial content to be available in only Hindi and English. Gujarati won't be a hurdle except consuming extra space when being eventually deployed. Hence we may need a mechanism to only load specific languages.

**Comment by cyberorg** [comment]
Hindi added, installing languages separately is not straightforward to implement so English, Gujarati and Hindi are all available.

**Comment by intelliant01** [comment]
There shouldn't be the rush to close an issue when all that is required is not accomplished. 

We can close this when separate language content installation has been achieved as we shall need support for various languages and it is not feasible to host all for everyone on the same mss.

**Comment by cyberorg** [comment]
OK, reassigning as whatever I could do is accomplished.

Reference for further development: http://spoken-tutorial.org/cdcontent/

1. Download each available language courses separately
2. Create separate mss offline page index(issue #26) for each of the languages installed

Will customize it with needed languages for mass deployments, effort needed to create per language bundle is not justified for demo servers or lesser number deployments or amount of space saved per language.

**Comment by intelliant01** [comment]
> Will customize it with needed languages for mass deployments, effort needed to create per language bundle is not justified for demo servers or lesser number deployments or amount of space saved per language.

@cyberorg That's exactly what I had meant by the following above - 
> Gujarati **won't be a hurdle** except consuming extra space **when being eventually deployed**. Hence we **may need a mechanism** to only load specific languages.

Have created #40 to handle this exclusively.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#5
