### ISSUE TITLE
Modularise loading of RACHEL content 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#37]
For example, the wikipedia for schools integrated into RACHEL is not sufficient for most current project usage scenarios presented by teachers / assigned to students, such as when researching for "PM of India" or the "Ebola virus" and some other scenarios.
 
Hence we must only load whatever modules are most useful from the RACHEL repo - http://dev.worldpossible.org/cgi/rachelmods.pl

**Comment by cyberorg** [comment]
Only load whatever modules are most useful from the RACHEL repo requires "rachel server" which is different from static rachel usb we are using, there is no known deb packages for ubuntu available as of now so not possible to implement it. 

Edit mss/rachel/RACHEL/index.html and remove mss/rachel/RACHEL/modules/<module> as per requirement.

Use Xowa if the latest and complete wikipedia is required. To add/update use xowa interface.

cd /var/www/html/web/xowa
sudo ./xowa.sh

**Comment by intelliant01** [comment]
@cyberorg will close it when something sustainable and acceptable has been implemented. It is again about how the install server and the mss will require modifications for the same.

(Don't bother closing it  and others till the story's goal is achieved and I suggest that the status be determined by the story owner. And yes surely these may be moderated and closed if left dangling across some review period.)

**Comment by cyberorg** [comment]
Rachel server has the modular installation, MSS will not be integrating that so don't see any reason for this issue to be tracked here.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#3
