### ISSUE TITLE
Devise mechanism to do a differential update of content, base distribution and applications

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#38]
It is needed to devise a mechanism to *incrementally* update content such as wikipedia, RACHEL, KA-lite as and when certain updates are available and we have subscribers with MSS connected to the Internet for such periodic updates for offline usage.

**Comment by cyberorg** [comment]
Use mechanism provided by upstream(xowa and kalite has built in) or request for such features on upstream project where it does not exist, there is no way for us to implement such features.

**Comment by intelliant01** [comment]
@cyberorg don't bother until it is assigned to you. 
No single person's limitations shall become the norm across the project. However thanks for your inputs and feel free to express yourself to the extent appropriate.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#4
