### ISSUE TITLE
Integrate an LMS such as Moodle

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#39]
An LMS such as Moodle will be of great utility to the users of the MSS, expecially for those who want to use this as a custom weaved educational content platform or as an online evaluation tool for computer or even other subjects.
There has been a request for the same from multiple sources.

**Comment by cyberorg** [comment]
Assign to me when you have the bundle ready for deployment.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#11
