### ISSUE TITLE
Devise mechanism to load only a specific language of spoken-tutorial content 

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#40]
Each language of s-t content is approx 2-3 GB. In all scenarios loading content in first and if required, additionally in second language shall suffice. 
Hence if we have such a dynamic mechanism to specify content language while installing the MSS, we shall be able to save some valuable space for other utilities and features.

**Comment by cyberorg** [comment]
Use the mechanism provided by upstream project as mentioned in https://github.com/cyberorg/mss/issues/36#issuecomment-303999654 i.e, download language specific bundle and use indexer to add each language specific icon.

**Comment by intelliant01** [comment]
@cyberorg this task is about how to integrate the process into the MSS installer. So leave it open. You need not bother until it is assigned to you.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#2
