### ISSUE TITLE
Install zabbix monitoring server to track MSS usage

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#41]
Would be best to install a Zabbix server on an AWS EC2 instance. If feasible must try to install on the same server as which hosts the MSS website.

Some links which may be explored further and followed - 

* http://www.endlick.com/install-zabbix-on-an-aws-instance-with-amazon-linux/
* https://www.skyarch.net/blog/?p=8557&lang=en
* https://aws.amazon.com/marketplace/pp/B01JZ0AJW4

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#29

**Comment by cyberorg** [comment]
Ref: sqlite corruption: https://support.zabbix.com/browse/ZBX-6036
