### ISSUE TITLE
Versioning of MSS releases needed

### ISSUE THREAD

**Issue by intelliant01** [RechercheTech/mss-doc#44]
With incremental improvements and simultaneous deployments happening we need to document and keep track of each small release related to MSS especially when it is being synced to the PROD install server.

This will be very helpful when we have to start debugging a particular MSS unit.
 
Helpful link: http://semver.org/

**Comment by cyberorg** [comment]
https://github.com/RechercheTech/changelog

**Comment by intelliant01** [comment]
@cyberorg Will the changelog be available on the installed MSS instance? Without that or some form of version mech it will be difficult to track and debug MSS units as I always see a lot of fluidity in our development and rapid enhancements even going forward.

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#32
