### ISSUE TITLE
Improve user creation documentation

### ISSUE THREAD

**Issue by geets04** [RechercheTech/mss-doc#49]
Update this section http://mss-doc.readthedocs.io/en/latest/01-User%20Management.html#via-gui . Add explanation related to legacy client.

Ref: https://github.com/RechercheTech/mss/issues/42

**Comment by intelliant01** [comment]
@geets04 Mass user creation may still need further improvement. Do review.

**Comment by intelliant01** [comment]
@geets04 Review of mass user creation steps needs to be done.

**Comment by intelliant01** [comment]
Steps for user creation via terminal result in a deactivated user. It needs to be activated again via GUI. This needs to be corrected by including steps for setting of password for the user.

**Comment by intelliant01** [comment]
Commit 3003dca15c7b463f21edc97a9eda1ee84ecac6e3 closes this.
