### ISSUE TITLE
Add new gujarati translated spoken-tutorial

### ISSUE THREAD

**Issue by cyberorg** [RechercheTech/mss-doc#8]
Please mention which ones, as far as I can see all the available ones are already there.

**Comment by intelliant01** [comment]
Not sure exactly which but if any new then they could be added. Also for example there is some difference or update required in content for scilab. Likewise updates may needed to be synced. Depending on the process being used to sync these this process may be feasible.

**Comment by cyberorg** [comment]
Closing this for now, we will include if any module comes to our attention that has got translation,

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/offlinewebinfra#10

**Comment by intelliant01** [comment]
This issue was moved to RechercheTech/mss#8
